# Site settings
title: Living Water Christian Reformed Church
email: jhwang@livingwatercrc.org
description: "Living Water CRC is a church plant in Grand Rapids, MI.  Our mission is to be a loving community, called to glorify God and raise disciples, who actively live the Gospel in the world."
baseurl: ""
url: "http://livingwatercrc.org"

# Build settings
markdown: kramdown
permalink: pretty

timezone: "America/New_York"

google_analytics_id: ""

# include: [ js ]
exclude: [ README.md ]

permalink: /blog/:title

sass:
  sass_dir: "_scss"
  css_dir: "../css"
  images_dir: "images"
  javascripts_dir: "javascripts"

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      layout: "default"
  -
    scope:
      path: "css"
    values:
      layout: ""